-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ADMINISTRADOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'OPERADOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'COMERCIAL';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'TECNICO';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'POS_VENDA';
